GET http://localhost:3000/api/blogs

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "test5",
    "author": "author4",
    "url": "www.test4.com",
    "likes":548
    }