GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbDIiLCJpZCI6IjYzZjg5ZjhhYzhmZDk3NjllMmY0NzhkYSIsImlhdCI6MTY3Nzg1OTIxM30.DR0cCVNbFIu_d7Ur97ltm1BHbu5DgmpzHpLIQvGeNRY

###
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbDIiLCJpZCI6IjYzZjg5ZjhhYzhmZDk3NjllMmY0NzhkYSIsImlhdCI6MTY3Nzg1OTIxM30.DR0cCVNbFIu_d7Ur97ltm1BHbu5DgmpzHpLIQvGeNRY

{
    "title": "test23",
    "author": "author3",
    "url": "www.test4.com",
    "likes":56054
    }

###
DELETE http://localhost:3000/api/blogs/63ea1ff21ea51de468a7b420
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbDIiLCJpZCI6IjYzZWExZTFiODU3MDFjZjg4ZTg1YThkNiIsImlhdCI6MTY3NjI4NzUyMX0.5Vq14qKl96hGfiIMvSWmdfQBSPnn6W42wPT4AS_7HwA

###
POST http://localhost:3000/api/blogs/63efd59f433214f51101a9f0/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbDIiLCJpZCI6IjYzZjg5ZjhhYzhmZDk3NjllMmY0NzhkYSIsImlhdCI6MTY3Nzg1OTIxM30.DR0cCVNbFIu_d7Ur97ltm1BHbu5DgmpzHpLIQvGeNRY

{
    "content": "this one is even better"
}